### ISSUE TITLE
Crashes on channels==2.2.0

### ISSUE THREAD

**Issue by PazimGoyal** [CJWorkbench/channels_rabbitmq#26] opened 2020-11-03 10:43 UTC
Get following error when using channels==2.2.0
(rabbitMQ is working fine as is also used by celery and is working fine)

[2020-11-03 10:40:48,344: ERROR/ForkPoolWorker-1] Unhandled exception from aioamqp
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/channels_rabbitmq/connection.py", line 527, in _connect_forever
    await self._connect_and_run()
  File "/usr/local/lib/python3.6/site-packages/channels_rabbitmq/connection.py", line 592, in _connect_and_run
    await self._channel.close_event.wait()  # case 1, 2, 3
  File "/usr/local/lib/python3.6/asyncio/locks.py", line 283, in wait
    yield from fut
concurrent.futures._base.CancelledError
[2020-11-03 10:40:48,357: ERROR/ForkPoolWorker-1] error on dispatch
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aioamqp/protocol.py", line 316, in run
    await self.dispatch_frame()
  File "/usr/local/lib/python3.6/site-packages/aioamqp/protocol.py", line 264, in dispatch_frame
    frame_channel, frame = await self.get_frame()
  File "/usr/local/lib/python3.6/site-packages/aioamqp/protocol.py", line 251, in get_frame
    return await amqp_frame.read(self._stream_reader)
  File "/usr/local/lib/python3.6/site-packages/aioamqp/frame.py", line 78, in read
    data = await reader.readexactly(7)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 674, in readexactly
    yield from self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 464, in _wait_for_data
    yield from self._waiter
concurrent.futures._base.CancelledError

**Comment by adamhooper** [comment] 2020-11-03 14:23
Thank you for the report! Could you please describe how to reproduce this error?

One thing that looks odd to me is `ForkPoolWorker`. Fork-pool workers shouldn't run async code. Are you calling `async_to_sync()` from within a Celery task? That isn't supported -- see #25.

**Comment by adamhooper** [comment] 2020-12-23 15:27
Closing because there's been no answer in six weeks. Please add details if you'd like to re-open :)

**Closed by adamhooper** 2020-12-23 15:27 UTC
Labels: question
