### ISSUE TITLE
assert "!" in channel

### ISSUE THREAD

**Issue by chrislondon** [CJWorkbench/channels_rabbitmq#27] opened 2020-11-18 06:53 UTC
I installed channels with RabbitMQ in my Django 3.1.3 app

```
channels==3.0.2
channels_rabbitmq==1.2.1
```

I set up channels with the following settings:

```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_rabbitmq.core.RabbitmqChannelLayer",
        "CONFIG": {
            "host": "amqp://user:pass@127.0.0.1:5672/vhost"
        },
    },
}
```

Following the channels tutorial (https://channels.readthedocs.io/en/stable/tutorial/part_2.html) I try running the following in my Django shell:

```
>>> import channels.layers
>>> channel_layer = channels.layers.get_channel_layer()
>>> from asgiref.sync import async_to_sync
>>> async_to_sync(channel_layer.send)('test_channel', {'type': 'hello'})
```

I get the following error:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 147, in __call__
    return call_result.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 212, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/channels_rabbitmq/core.py", line 153, in send
    assert "!" in channel
AssertionError
```

Thoughts?

**Comment by adamhooper** [comment] 2020-11-18 12:25
The tutorial is requesting that you use Channels as a work queue. `channels_rabbitmq` doesn't support that feature, and the rest of the tutorial doesn't use it. You can skip that step and continue with the rest of the tutorial.

Duplicate of #11.

I'm going to add a paragraph about the tutorial to the README, then I'll close this issue.

**Comment by adamhooper** [comment] 2021-01-10 17:31
Closing: this is on the `aiormq` branch, which I'll be releasing very soon.

**Closed by adamhooper** 2021-01-10 17:31 UTC
